apiVersion: apps/v1
kind: Deployment
metadata:
  name: brisk-queue
  namespace: {{ .Values.namespace }}
  labels:
    app: brisk-queue
    environment: dev
    release: {{ .Values.version }}
    tier: backend
    track: stable
spec:
  replicas: {{ .Values.queue.deployment.replicaCount }}
  selector:
    matchLabels:
      app: brisk-queue
      environment: dev
      release: {{ .Values.version }}
      tier: backend
      track: stable
  template:
    metadata:
      name: brisk-queue
      labels:
        app: brisk-queue
        environment: dev
        release: {{ .Values.version }}
        tier: backend
        track: stable
    spec:
      containers:
          - name : brisk-gatequeueway
            image: {{ .Values.queue.deployment.image.repository }}:{{ .Values.queue.deployment.image.tag }}
            imagePullPolicy: {{ .Values.queue.deployment.image.pullPolicy }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: brisk-queue
  namespace: {{ .Values.namespace }}
  labels:
      app: brisk-queue
      environment: dev
      release: {{ .Values.version }}
      tier: backend
      track: stable
spec:
  type: {{ .Values.queue.service.type }}
  ports:
      - name: "tcp-80-8080-brisk-queue"
        protocol: TCP
        port: 80
        targetPort: 8080
  selector:
      app: brisk-queue
      environment: dev
      release: {{ .Values.version }}
      tier: backend
      track: stable
#---
#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: brisk-queue
#  namespace: {{ .Values.namespace }}
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: brisk-queue
#  minReplicas: {{ .Values.queue.deployment.replicaCount }}
#  maxReplicas: 99
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        targetAverageUtilization: 50