# Default values for OpenBrisk.
# Declare variables to be passed into your templates.

version: 0.0.1

# Controller configuration.
controller:
  deployment:
    replicaCount: 3
    image: 
      repository: openbrisk/brisk-controller
      tag: latest
      pullPolicy: IfNotPresent
  service:
    type: ClusterIP

# Gateway configuration.
gateway:
  deployment:
    replicaCount: 3
    image:
      repository: openbrisk/brisk-gateway
      tag: latest
      pullPolicy: IfNotPresent
  service:
    type: ClusterIP      

# Queue configuration.
queue:
  deployment:
    replicaCount: 3
    image:
      repository: openbrisk/brisk-queue
      tag: latest
      pullPolicy: IfNotPresent
  service:
    type: ClusterIP
